
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 11 20:28:51 GMT-03:00 2017
//----------------------------------------------------

package sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 4;
  public static final int IDENTIFIER = 94;
  public static final int GT = 67;
  public static final int IMPLEMENTS = 34;
  public static final int TIO = 85;
  public static final int NOTEQ = 72;
  public static final int PLUSEQ = 80;
  public static final int RBRACK = 62;
  public static final int CATCH = 51;
  public static final int COMMA = 13;
  public static final int RBRACE = 15;
  public static final int THROW = 49;
  public static final int RPAREN = 18;
  public static final int LBRACK = 61;
  public static final int LT = 66;
  public static final int DOUBLE = 9;
  public static final int LBRACE = 14;
  public static final int TRANSIENT = 31;
  public static final int LPAREN = 17;
  public static final int XOREQ = 83;
  public static final int PROTECTED = 23;
  public static final int INTEGER_LITERAL = 89;
  public static final int NOT = 58;
  public static final int FINAL = 28;
  public static final int FLOAT = 8;
  public static final int PACKAGE = 20;
  public static final int EQ = 16;
  public static final int BOOLEAN_LITERAL = 91;
  public static final int MOD = 60;
  public static final int AMPERSANDEQ = 87;
  public static final int CLASS = 32;
  public static final int SUPER = 36;
  public static final int ABSTRACT = 27;
  public static final int NATIVE = 29;
  public static final int LONG = 6;
  public static final int PLUS = 56;
  public static final int QUESTION = 76;
  public static final int WHILE = 44;
  public static final int AMPERSANDAMPERSAND = 88;
  public static final int EXTENDS = 33;
  public static final int INTERFACE = 37;
  public static final int CHAR = 7;
  public static final int BOOLEAN = 2;
  public static final int SWITCH = 40;
  public static final int DO = 43;
  public static final int FOR = 45;
  public static final int RSHIFTEQ = 82;
  public static final int DIV = 59;
  public static final int PUBLIC = 22;
  public static final int RETURN = 48;
  public static final int MULT = 12;
  public static final int ELSE = 39;
  public static final int TRY = 50;
  public static final int BREAK = 46;
  public static final int GTEQ = 69;
  public static final int AMPERSAND = 86;
  public static final int DOT = 10;
  public static final int INT = 5;
  public static final int STRING_LITERAL = 93;
  public static final int NULL = 95;
  public static final int EQEQ = 71;
  public static final int EOF = 0;
  public static final int SEMICOLON = 11;
  public static final int THIS = 35;
  public static final int DEFAULT = 42;
  public static final int MULTEQ = 77;
  public static final int IMPORT = 21;
  public static final int OROREQ = 75;
  public static final int MINUS = 57;
  public static final int FLOAT_LITERAL = 90;
  public static final int LTEQ = 68;
  public static final int OR = 74;
  public static final int error = 1;
  public static final int URSHIFT = 65;
  public static final int SYNCHRONIZED = 30;
  public static final int DIVEQ = 78;
  public static final int FINALLY = 52;
  public static final int CONTINUE = 47;
  public static final int IF = 38;
  public static final int INSTANCEOF = 70;
  public static final int MODEQ = 79;
  public static final int MINUSMINUS = 55;
  public static final int COLON = 19;
  public static final int CHARACTER_LITERAL = 92;
  public static final int OREQ = 84;
  public static final int CASE = 41;
  public static final int PLUSPLUS = 54;
  public static final int NEW = 53;
  public static final int THREADSAFE = 25;
  public static final int RSHIFT = 64;
  public static final int BYTE = 3;
  public static final int PRIVATE = 24;
  public static final int STATIC = 26;
  public static final int LSHIFT = 63;
  public static final int XOR = 73;
  public static final int MINUSEQ = 81;
}

